#!/bin/sh

APPDIR=$(readlink -f "$0")
APPDIR=$(dirname "$APPDIR")
java -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR:$APPDIR/lib/Network_Simulator.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-i586.jar:$APPDIR/lib/gluegen-rt-natives-linux-i586.jar:$APPDIR/lib/G4P.jar:$APPDIR/lib/antlr4-runtime-4.6.jar:$APPDIR/lib/commons-lang3-3.5.jar:$APPDIR/lib/jgraph-5.13.0.0.jar:$APPDIR/lib/jgrapht-core-1.1.0.jar:$APPDIR/lib/jgrapht-demo-1.1.0.jar:$APPDIR/lib/jgrapht-ext-1.1.0-uber.jar:$APPDIR/lib/jgrapht-ext-1.1.0.jar:$APPDIR/lib/jgrapht-io-1.1.0-uber.jar:$APPDIR/lib/jgrapht-io-1.1.0.jar:$APPDIR/lib/JGrapht.jar" Network_Simulator "$@"
